version: '3.8'
services:
  remmy:
    container_name: remmy
    image: remmy
    restart: always
    build: .
    env_file: .env
    ports:
      - 7500:7500
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: # named volumes can be managed easier using docker-compose
